AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "node_modules/**/*"
    - ".next/**/*"
    - "var/**/*"
    - "build/**/*"

AsciiComments:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Metrics/MethodLength:
  Max: 60
  Exclude:
    - "src/app_launcher/al_task_exec.rb" # TODO
    - "src/launcher.rb"
    - "spec/large/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "src/launcher.rb"
    - "spec/**/*.rb"

Style/Documentation:
  Enabled: false

tyle/OptionalBooleanParameter:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html
Metrics/AbcSize:
  Max: 33
  Exclude:
    - "src/launcher.rb"
    - "src/app_launcher/al_task_exec.rb" # TODO

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - "src/launcher.rb"
    - "src/lib/executor.rb" # TODO
    - "src/app_launcher/al_task_exec.rb" # TODO

Metrics/PerceivedComplexity:
  Exclude:
    - "src/launcher.rb"
    - "src/lib/executor.rb" # TODO
    - "src/app_launcher/al_task_exec.rb" # TODO

Style/ClassVars:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false
